# TensorFlow Basics

In [1]:
import tensorflow as tf

C:\Users\ASUS\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
# Make sure you are using 1.3 for exact sytnax matching!
print(tf.__version__)

1.10.0


## Tensors

In [3]:
hello = tf.constant('Hello')

In [4]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [5]:
world = tf.constant('World')

In [6]:
result = hello + world

In [7]:
result

<tf.Tensor 'add:0' shape=() dtype=string>

In [8]:
with tf.Session() as sess:
    print(sess.run(result))

b'HelloWorld'


In [9]:
type(result)

tensorflow.python.framework.ops.Tensor

In [10]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [11]:
result

b'HelloWorld'

** Computations **

In [12]:
tensor_1 = tf.constant(1)
tensor_2 = tf.constant(2)

In [13]:
type(tensor_1)

tensorflow.python.framework.ops.Tensor

In [14]:
tensor_1 + tensor_2

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [15]:
sess

In [16]:
sess.close()

## Operations

In [17]:
const = tf.constant(10)

In [18]:
fill_mat = tf.fill((4,4),10)

In [19]:
myzeros = tf.zeros((4,4))

In [20]:
myones = tf.ones((4,4))

In [21]:
myrandn = tf.random_normal((4,4),mean=0,stddev=0.5)

In [22]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [23]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

## Interactive Session

Useful for Notebook Sessions

In [24]:
# Only run this cell once!
sess = tf.InteractiveSession()

In [25]:
for op in my_ops:
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 0.04579936  0.04071695 -0.00634879 -0.69616866]
 [ 0.82263994 -0.15800312  0.5857488  -0.11424164]
 [-0.71675897 -0.07152665  0.31186858  0.3046136 ]
 [-0.4672863   0.21686998 -0.25242186 -1.1830246 ]]


[[0.900617   0.40492558 0.21358633 0.18282616]
 [0.8144208  0.1902126  0.20763409 0.05647767]
 [0.10335183 0.32334816 0.0345397  0.4808091 ]
 [0.86519635 0.80671597 0.52856314 0.12096465]]




## Matrix Multiplication

In [26]:
a = tf.constant([ [1,2],
                  [3,4] ])

In [27]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [28]:
b = tf.constant([[10],[100]])

In [29]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [30]:
result = tf.matmul(a,b)

In [31]:
result.eval()

array([[210],
       [430]])